### ISSUE TITLE
More examples or tutorial series? 

### ISSUE THREAD

**Issue by amitahire** [numediart/ofxMotionMachine#4]
Hello, 

It would be wonderful if there were more examples or more of the tutorial series for MotionMachine.

There is only one about loading the motion file, How about playing the animation. bone trace and other features ?

Thanks.

**Comment by titsitits** [comment]
Hi Amit,

It would be wonderful indeed ;) I just uploaded a first tutorial example, and others should be coming soon. I would be glad to have your feedback on this first example.

Mickaël

**Comment by wamapi89** [comment]
Hello,
is there any tutorial on implementing an annotation using motionmachine?

**Comment by titsitits** [comment]
Hi,

I just uploaded a new tutorial (mmTutorial_4_Annotation), I would be glad to have your feedback.

Mickaël

**Comment by wamapi89** [comment]
Thank you, it would help a lot. Alright, i will give you a feedback later

**Comment by leilaUEA** [comment]
Hi Michael,

Thanks for uploading examples. I have an issue reading the joint data in the .bvh files in the tutorial with the name: "mmTutorial_1_DataTypes", there is an animation.bvh file in the example data folder, the program cannot find the position of the right hand and shows the ground, it can find the pelvis. I tried another bvh file from CMU website and still the same problem. Do you know what is the possible source of the problem? 

Thank you very much,
Leila

**Comment by titsitits** [comment]
Hi, 

The animation.bvh is in local coordinates, and must be converted to global coordinates, like this:
```
    myTrack.load(getExampleDataPath() + "animation.bvh");
    myTrack.localToGlobal();
```

When I comment the second line I have something similar to what you said.
I hope it helps!

Mickaël

**Comment by leilaUEA** [comment]
Thank you very much for your prompt response, that was really helpful! 

Can I take your time asking another question, when using external bvh files, the human figure is shown small in the output window, do I need to scale the skeleton before using the data in motion machine?

For example I took some files from following website:
https://sites.google.com/a/cgspeed.com/cgspeed/motion-capture/cmu-bvh-conversion

Thank you very much in advance,

Best regards,
Leila

**Comment by thiravet** [comment]
Hi Leila,
You can scale your data in motionmachine by adding the line (<scale> has to be replaced by a float value) after loading the file: 

myTrack.position = myTrack.position * <scale>;

best regards

Thierry

**Comment by thiravet** [comment]
and perhaps you will need to add node names used in your bvh file in SynoList.txt (you can find this file in bin/data/resources )

**Comment by leilaUEA** [comment]
Hi Thierry,
Many thanks for your response and also mentioning the SynoList, that would be very useful!
Best regards,
Leila
