### ISSUE TITLE
projectGenerator-osx-MoMa would not run because of missing Libraries 

### ISSUE THREAD

**Issue by cerkut** [numediart/ofxMotionMachine#7]
projectGenerator-osx-MoM would not launch with complaints on libnode.dylib 
ofxMotionMachine/projectGenerator-osx-MoMa/projectGenerator.app/Contents/Frameworks/Electron Framework.framework/Versions/A/ does not have the Libraries folder that should contain libnode.dylib and ffmpegsumo.so. Copying this folder from oF solves the issue. 
Thanks.

**Comment by thiravet** [comment]
I have committed the two missing libraries. Thanks for this report.

Thierry
