### ISSUE TITLE
how do I compile mmEmptyExample on a Mac?

### ISSUE THREAD

**Issue by cerkut** [numediart/ofxMotionMachine#8]
Hi, ofxMotionMachine looks very promising for movement research, thanks for developing it.
But I don't get how I should compile the mmEmptyExample. The video shows MotionMachine (not ofxMotionMachine) and finds an oF folder to copy export / and lib folders from oF. Is that for a separate download? The link (www.motionmachine.org) redirects to http://numediart.org/tools/motionmachine/ with 404? If not, where is moma.h? 
The operations are very unusual for an oF addon, please help for compiling the mmEmptyExample on Mac? 
Thanks -- Cumhur

**Comment by thiravet** [comment]
Hi,

thanks for your interest.
The video is unfortunately deprecated. For the current version,  we have adapted the architecture to transform MotionMachine into a usual of addon. You have just to copy the ofxMotionMachine in the openframeworks addon directory.
I will check for the missing libraries that you reported as soon as possible. Currently we have no one that works frequently under mac os, then we are interested by your feedback.

best regards
Thierry

**Comment by cerkut** [comment]
Thanks Thierry, great to know ofxMotionMachine is (or becoming one) a regular oFx add-on and no other copying is needed than the addon itself. 

I noted that the last release of MotionMachine was stand-alone; all of its examples compiled fine when I copied `export` and `lib` folders from the current oF (of_v0.9.8_osx_release, with 200+ warnings about depreciations from 0.9.2 onwards, but that's fine, I can fix them). 

I'll further experiment with the current ofxMotionMachine on Mac and Win, and gladly report on the Mac progress. Awesome work, thanks.

**Comment by cerkut** [comment]
The empty project I created with the bundled ProjectGenerator including the ofxMotionMachine compiled on Mac 👍Now off to the nice tutorials you have prepared. Thanks.
